a = input('Digite algo: ')
print('O tipo primitivo desse valor e ', type(a))
print('So tem espacos ? ', a.isspace())
print('E um numero ? ', a.isnumeric())
print('E alfabetico ?', a.isalpha())
print('e alfanumerico ?', a.isalnum())
print('Esta em maisucula ? ', a.isupper())
print('Esta em minuscula ?', a.islower())
print('Esta capitalizada ?', a.istitle())

