n1 = int(input('Um Valor: '))
n2 = int(input('Outro Valor: '))
print('A Soma vale {}'.format(n1 + n2))
print('A multiplicacao vale {}'.format(n1 * n2))
print('A Divisao vale {}'.format(n1 / n2))
print('A Divisao inteira vale {}'.format(n1 // n2))
print('O resto da Divisao e igual a {}'.format(n1 % n2))
print('A potencia de {} elevado a {}, e {}'.format(n1, n2, n1 ** n2))